services:
  postgres:
    image: postgres:16
    container_name: chaos-postgres
    restart: always
    environment:
      POSTGRES_USER: chaosuser
      POSTGRES_PASSWORD: chaospass
      POSTGRES_DB: chaosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: