spring:
  profiles:
    active: chaos-monkey
  application:
    name: chaos-monkey-for-spring-poc
  datasource:
    url: jdbc:postgresql://localhost:5432/chaosdb
    username: chaosuser
    password: chaospass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

chaos:
  monkey:
    enabled: true
    watcher:
      restController: true
      service: true
      repository: true
    assaults:
      latencyActive: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"