spring:
  profiles:
    active: chaos-monkey
  application:
    name: chaos-monkey-for-spring-poc
  datasource:
    url: jdbc:postgresql://localhost:5432/chaosdb
    username: chaosuser
    password: chaospass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

chaos:
  monkey:
    enabled: true
    watcher:
      restController: true
      service: true
      repository: true
    assaults:
      level: 2
      deterministic: true
      latencyActive: true
      latencyRangeStart: 2000
      latencyRangeEnd: 3000
      exceptionsActive: true
      memoryActive: true
      memoryMillisecondsHoldFilledMemory: 10000
      cpuActive: true
      cpuMillisecondsHoldLoad: 10000

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"